api/urls.py
from django.urls import include, path
from . import views

app_name='api'
urlpatterns = [
    path('clients', views.Users_APIView.as_view()),
    path('clients/<pk>', views.Users_APIView_Detail.as_view()),
    path('token', views.TestView.as_view()),
]

cars/urls.py
from django.urls import include, path
from . import views
from django.views.generic import ListView
from django.conf import settings
from django.conf.urls.static import static
app_name='cars'

urlpatterns = [
    path("", views.IndexListView.as_view(), name="listacoches"),
    path("nuevo", views.cocheCreateView.as_view(), name="nuevocoche"),
    path('<int:pk>', views.verDetailView.as_view(), name="vercoche"),
    path('editar/<int:pk>', views.editarUpdateView.as_view(), name="editarcoche"),
    path("borrar/<pk>", views.borrarDeleteView.as_view(), name="borrarcoche")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reparations/urls.py
from django.urls import include, path
from . import views

app_name='reparations'

urlpatterns = [
    path("reparate/<int:pk>", views.reparateView, name="reparate"),
    path("reparations", views.reparationView.as_view(), name="reparations"),
    path("mechanic_reparations", views.reparationMechanicView.as_view(), name="Mreparations"),
    path("mechanic_reparate", views.reparateMechanicView.as_view(), name="Mreparate"),
    path("mechanic_reparate/<int:pk>", views.reparMechanicView, name="Mrepar"),
    path("report/<int:pk>", views.informeView.as_view(), name="report"),
]

teloreparo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import handler404, handler500

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('contact', views.contactView, name="contact"),
    path('account', include('account.urls', namespace='account')),
    path('coches/', include('cars.urls', namespace='cars')),
    path('noticias/', include('notices.urls', namespace='notices')),
    path('api/', include('api.urls', namespace='api')),
    path('reparacion/', include('reparations.urls', namespace='reparations')),
]
handler404 = views.error_404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from django.db import models

# Create your models here.

class coche(models.Model):
    Matricula = models.CharField(max_length=10, unique=True, verbose_name="Matrícula")
    Marca = models.CharField(max_length=50, blank=True, null=True)
    Modelo = models.CharField(max_length=50, blank=True, null=True)
    Color = models.CharField(max_length=50, blank=True, null=True)
    FechaMatriculacion = models.DateField(verbose_name="Fecha de la matriculación")
    Imagen = models.ImageField(upload_to='coches/', blank=True, null=True)
    Dueno = models.ForeignKey("account.User", on_delete=models.CASCADE, verbose_name="Dueño")
    def __str__(self):
        return self.Matricula

cars/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from django.urls import reverse_lazy
from .models import coche
import datetime

from account.decorators import client_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.
@method_decorator([login_required, client_required], name='dispatch')
class IndexListView(ListView):
    model = coche
    template_name='cars/index.html'
    context_object_name = 'coches'
    paginate_by=8
    def get_queryset(self, *args, **kwargs):
        return coche.objects.filter(Dueno=self.request.user.id)
@method_decorator([login_required, client_required], name='dispatch')
class cocheCreateView(CreateView):
    model = coche
    template_name = "cars/create.html"
    fields=['Matricula', 'Marca', 'Modelo', 'Color', 'FechaMatriculacion','Imagen']
    success_url = reverse_lazy('cars:listacoches')
    anos = []
    for i in range(30):
        anos.append(datetime.date.today().year - i)
    def get_form(self):
        from django.forms.widgets import SelectDateWidget
        form = super(CreateView, self).get_form()
        form.fields['FechaMatriculacion'].widget = SelectDateWidget(years=self.anos)
        return form
    def form_valid(self, form):
        form.instance.Dueno = self.request.user
        return super(cocheCreateView, self).form_valid(form)
@method_decorator([login_required, client_required], name='dispatch')
class verDetailView(DetailView):
    model = coche
    template_name="cars/detail.html"
    success_url = reverse_lazy('cars:listacoches')
@method_decorator([login_required, client_required], name='dispatch')
class editarUpdateView(UpdateView):
    anos = []
    for i in range(30):
        anos.append(datetime.date.today().year - i)
    model = coche
    template_name = "cars/edit.html"
    fields=['Matricula', 'Marca', 'Modelo', 'Color', 'FechaMatriculacion','Imagen']
    success_url = reverse_lazy('cars:listacoches')
    def get_form(self):
        from django.forms.widgets import SelectDateWidget
        form = super(UpdateView, self).get_form()
        form.fields['FechaMatriculacion'].widget = SelectDateWidget(years=self.anos)
        return form
    def form_valid(self, form):
        form.instance.Dueno = self.request.user
        return super(editarUpdateView, self).form_valid(form)
@method_decorator([login_required, client_required], name='dispatch')
class borrarDeleteView(DeleteView):
    model = coche
    template_name = "cars/delete.html"
    success_url = reverse_lazy('cars:listacoches')

cars/templates/cars/create.html
{% extends 'base.html' %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Todos tus coches{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h2>Nuevo coche</h2>
      </div>
    <div class="card-body pb-0">
  <form action="" method="post">
      {% csrf_token %}
      <table>
          {{ form.as_table}}
      </table>
      <br>
  </div>
  <div class="card-footer">
    <a href="{% url 'cars:listacoches' %}" class="btn btn-default">Volver</a>
    <button type="submit" class="btn btn-primary">Insertar Coche</button>
  </div>
</form>
</div>
{% endblock %}

cars/templates/cars/delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Te lo reparo{% endblock %} 
{% block header %}Borrado de coche.{% endblock %} 
{% block content %}
<div class="card card-solid">
  <div class="card-body pb-0">
    ¿Estás seguro de querer borrar "{{ object }}"?
  </div>
  <div class="card-footer">
    <form method="post">
      {% csrf_token %}
      <a href="{% url 'cars:listacoches' %}" class="btn btn-default"
        >Cancelar</a
      >
      <input type="submit" value="Confirmar" class="btn btn-success" />
    </form>
  </div>
</div>
{% endblock %}

cars/templates/cars/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Coches{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h2>Todos los detalles del maravilloso {{ coche.Modelo }}</h2>
      </div>
    <div class="card-body pb-0">
        <div>Matricula: {{ coche.Matricula }}</div>
        <div>Marca: {{ coche.Marca }}</div>
        <div>Modelo: {{ coche.Modelo }}</div>
        <div>Color: {{ coche.Color }}</div>
        <div>FechaMatriculacion: {{ coche.FechaMatriculacion }}</div>
        <div>Imagen: <img
                    src="{% if coche.Imagen %}{{ coche.Imagen.url }}{% else %}{% static 'logo.jpg' %}{% endif %}"
                    alt="Imagen del coche"
                    width="100%"
                    height="100%"
                    class="img-fluid mb-2"
                  /></div>
      <br>
  </div>
  <div class="card-footer">
    <a href="{% url 'cars:listacoches' %}" class="btn btn-default">Volver</a>
    <a href="{% url 'cars:editarcoche' coche.id %}" class="btn btn-info">Editar</a>
  </div>
</div>
{% endblock %}

cars/templates/cars/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Todos tus coches{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h4>Modifica el coche {{ coche.Matricula }}</h4>
    </div>
    <div class="card-body pb-0">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
    </div><div class="card-footer">
    <a href="{% url 'cars:listacoches' %}" class="btn btn-default">Volver</a>
    <input type="Submit" value="Actualizar" class="btn btn-primary">
  </div>
  </form>
</div>
{% endblock %}

cars/templates/cars/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Te lo reparo{%endblock %} 
{% block header %}Todos tus coches{% endblock %} 
{% block content %}
<div class="card card-solid">
  <div class="card-header ui-sortable-handle">
    <h4 class="card-title">Sus coches, {{ user.first_name }}.</h4>
    <div class="card-tools">
      <div class="pagination pagination-sm">
        {% if coches %}
          {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link">«</a>
          {% endif %}
  
          <span class="current page-link">
              Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" style="text-decoration:none;" class="page-link">»</a>
          {% endif %}
          {% endif %}
  </div>
    </div>
  </div>
  <div class="card-body pb-0">
    <div class="row d-flex align-items-stretch">
      {% for coche in coches %}
      <div class="col-12 col-sm-6 col-md-3">
        <div class="card bg-light">
          <a href="{% url 'cars:vercoche' coche.id %}">
            <div class="card-header text-muted border-bottom-0">
              {{ coche.Matricula }}
            </div>
            <div class="card-body pt-0">
              <div class="row">
                <div class="col-7">
                  <p class="text-muted text-sm">
                    <b>Marca: </b>{{ coche.Marca }}</b>
                  </p>
                  <p class="text-muted text-sm">
                    <b>Modelo: </b>{{ coche.Modelo }}</b>
                  </p>
                  <p class="text-muted text-sm">
                    <b>Fecha de matriculación: </b><br />
                    {{ coche.FechaMatriculacion }}
                  </p>
                </div>
                <div class="col-5 text-center">
                  <img
                    src="{% if coche.Imagen %}
                        {{ coche.Imagen.url }}
                        {% else %}
                        {% static 'x.png' %}
                        {% endif %}"
                    alt="Imagen del coche"
                    width="100"
                    height="100"
                    class="img-fluid mb-2"
                  />
                </div>
              </div>
            </div>
          </a>
          <div class="card-footer">
            <div class="">
              <a href="{% url 'reparations:reparate' coche.id %}" class="btn btn-warning">Reparar</a>
              <a href="{% url 'cars:editarcoche' coche.id %}" class="btn btn-info">Editar</a>
              <a href="{% url 'cars:borrarcoche' coche.id %}" class="btn btn-danger float-right">Eliminar</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %} {% if not coches %}
      <p>No tienes coches actualmente, pulsa en el botón para incluirlo</p>
      {% endif %}
    </div>
  </div>
  <div class="card-footer">
    <a href="{% url 'cars:nuevocoche' %}" class="btn btn-success">Añadir coche</a>
  </div>
</div>
{% endblock %}