api/urls.py
from django.urls import include, path
from . import views

app_name='api'
urlpatterns = [
    path('clients', views.Users_APIView.as_view()),
    path('clients/<pk>', views.Users_APIView_Detail.as_view()),
    path('token', views.TestView.as_view()),
]

notices/urls.py
from django.urls import include, path
from . import views
from django.views.generic import ListView
from django.conf import settings
from django.conf.urls.static import static
app_name='notices'

urlpatterns = [
    path("", views.IndexListView.as_view(), name="listanoticias"),
    path("editar/<int:pk>", views.noticiaUpdateView.as_view(), name="editarnoticia"),
    path('<int:pk>', views.verDetailView.as_view(), name="vernoticia"),
    path('nueva', views.nuevaCreateView.as_view(), name="nuevanoticia"),
    path("borrar/<pk>", views.borrarDeleteView.as_view(), name="borrarnoticia")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teloreparo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import handler404, handler500

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index'),
    path('contact', views.contactView, name="contact"),
    path('account', include('account.urls', namespace='account')),
    path('coches/', include('cars.urls', namespace='cars')),
    path('noticias/', include('notices.urls', namespace='notices')),
    path('api/', include('api.urls', namespace='api')),
    path('reparacion/', include('reparations.urls', namespace='reparations')),
]
handler404 = views.error_404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notices/models.py
from django.db import models

# Create your models here.
class noticia(models.Model):
    Titulo = models.CharField(max_length=100, verbose_name="Titulo")
    Texto = models.TextField(blank=True, null=True)
    Foto = models.ImageField(upload_to='noticias/', blank=True, null=True)
    Autor = models.ForeignKey("account.User", on_delete=models.CASCADE, blank=True, null=True)
    Fcreacion = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name="Fecha de cración")
    Fmodificacion = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name="Fecha de modificación")
    def __str__(self):
        return self.Titulo

notices/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from .models import noticia

from account.decorators import mechanic_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.
@method_decorator([login_required, mechanic_required], name='dispatch')
class IndexListView(ListView):
    model = noticia
    template_name='notices/index.html'
    context_object_name = 'noticias'
    paginate_by=6
@method_decorator([login_required, mechanic_required], name='dispatch')
class verDetailView(DetailView):
    model = noticia
    template_name = "notices/detail.html"
    success_url = reverse_lazy('notices:listanoticias')
@method_decorator([login_required, mechanic_required], name='dispatch')
class noticiaUpdateView(UpdateView):
    model = noticia
    template_name = "notices/edit.html"
    fields=['Titulo', 'Texto', 'Foto']
    success_url = reverse_lazy('notices:listanoticias')
@method_decorator([login_required, mechanic_required], name='dispatch')
class nuevaCreateView(CreateView):
    model = noticia
    template_name = "notices/create.html"
    fields=['Titulo', 'Texto', 'Foto']
    success_url = reverse_lazy('notices:listanoticias')
    def form_valid(self, form):
        form.instance.Autor = self.request.user
        return super(nuevaCreateView, self).form_valid(form)
@method_decorator([login_required, mechanic_required], name='dispatch')
class borrarDeleteView(DeleteView):
    model = noticia
    template_name = "notices/delete.html"
    success_url = reverse_lazy('notices:listanoticias')

notices/templates/notices/create.html
{% extends 'base.html' %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Todos tus coches{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h2>Nueva noticia</h2>
      </div>
    <div class="card-body pb-0">
  <form action="" method="post">
      {% csrf_token %}
      <table>
          {{ form.as_table}}
      </table>
      <br>
  </div>
  <div class="card-footer">
    <a href="{% url 'notices:listanoticias' %}" class="btn btn-default">Volver</a>
    <button type="submit" class="btn btn-primary">Insertar noticia</button>
  </div>
</form>
</div>
{% endblock %}

notices/templates/notices/delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Te lo reparo{% endblock %} 
{% block header %}Borrado de coche.{% endblock %} 
{% block content %}
<div class="card card-solid">
  <div class="card-body pb-0">
    ¿Estás seguro de querer borrar "{{ object }}"?
  </div>
  <div class="card-footer">
    <form method="post">
      {% csrf_token %}
      <a href="{% url 'notices:listanoticias' %}" class="btn btn-default"
        >Cancelar</a
      >
      <input type="submit" value="Confirmar" class="btn btn-success" />
    </form>
  </div>
</div>
{% endblock %}

notices/templates/notices/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Todos tus coches{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h2>Todos los detalles de {{ noticia.Titulo }}.</h2>
      </div>
    <div class="card-body pb-0">
        <div>Titulo: {{ noticia.Titulo }}</div>
        <div>Texto: {{ noticia.Texto }}</div>
        <div>Fecha de modificación: {{ noticia.Fmodificacion }}</div>
        <div>Fecha de creacion: {{ noticia.Fcreacion }}</div>
        <div>Autor: {% if noticia.Autor %}{{ noticia.Autor }}{% else %}Anónimo{% endif %}</div>
        <div>Foto: <img src="{% if noticia.Foto %}{{ noticia.Foto.url }}{% else %}{% static 'logo.jpg' %}{% endif %}" alt="No se puede cargar la imagen" width="100%"></div>
      <br>
  </div>
  <div class="card-footer">
    <a href="{% url 'notices:listanoticias' %}" class="btn btn-default">Volver</a>
    <a href="{% url 'notices:editarnoticia' noticia.id%}" class="btn btn-info">Editar</a>
  </div>
</div>
{% endblock %}

notices/templates/notices/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Te lo reparo{% endblock %}
{% block header %}Noticias{% endblock %}
{% block content %}
<div class="card card-solid">
    <div class="card-header">
        <h4>Modifica la noticia {{ noticia.Titulo }}</h4>
    </div>
    <div class="card-body pb-0">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
    </div><div class="card-footer">
    <a href="{% url 'notices:listanoticias' %}" class="btn btn-default">Volver</a>
    <input type="Submit" value="Actualizar" class="btn btn-primary">
  </div>
  </form>
</div>
{% endblock %}

notices/templates/notices/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}Te lo reparo{%endblock %} 
{% block header %}Todos las noticias{% endblock %} 
{% block content %}
<div class="card card-solid">
  <div class="card-header ui-sortable-handle">
    <h4 class="card-title">Las noticias de teloreparo, ten cuidado porque las leerán los clientes.</h4>
    <div class="card-tools">
      <div class="pagination pagination-sm">
        {% if noticias %}
          {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link">«</a>
          {% endif %}
  
          <span class="current page-link">
              Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" style="text-decoration:none;" class="page-link">»</a>
          {% endif %}
          {% endif %}
  </div>
    </div>
  </div>
  </div>
  <div class="card-body pb-0">
    <div class="row d-flex align-items-stretch">
      {% for noticia in noticias %}
      <a href="{% url 'notices:vernoticia' noticia.id %}">
        <div class="col-12 col-sm-6 col-md-6">
          <div class="card bg-light">
            <div class="card-header text-muted border-bottom-0">
              {{ noticia.Titulo }}
            </div>
            <div class="card-header">{{ noticia.Texto }}</div>
            <div class="card-footer">
              <div class="">
                <a href="{% url 'notices:editarnoticia' noticia.id %}" class="btn btn-info">Editar</a>
                <a href="{% url 'notices:borrarnoticia' noticia.id %}" class="btn btn-danger float-right">Eliminar</a>
              </div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %} 
      {% if not noticias %}
      <p>No tienes coches actualmente, pulsa en el botón para incluirlo</p>
      {% endif %}
    </div>
  </div>
  <div class="card-footer">
    <a href="{% url 'notices:nuevanoticia' %}" class="btn btn-success">Añadir noticia</a>
  </div>
</div>
{% endblock %}